### ISSUE TITLE
Potentially dead code

### ISSUE THREAD

**Issue by Willt125** [VioletVillain/ZedAssembly#1]
Attempts to load the webpage, whether hosted local or not, loads indefinitely. Whether the page will load at all is questionable. It has been spinning for the last ~15 minutes (most recent attempt made 19:20 yesterday, and killed 19:34, with no known progress).

I am running Python 3.8, Firefox 84.0.2, Windows 10.

**Comment by Thraetaona** [comment]
Thanks for reporting, it appears that Firefox attempts to load and execute the script tag before loading the body and it causes all the interactions with the said html elements (getlElementById, etc) to return null (uncaught exception).  Although when I tested EXACT on Firefox before it worked fine.

Simply putting the script tag at the bottom of the html file (So that the body is created before being accessed) solves this issue.

---

[Should work properly now, let me know if it's still not working](https://thraetaona.github.io/EXACT/)

[Relevant release](https://github.com/Thraetaona/EXACT/releases/tag/1.0.1)

**Comment by Thraetaona** [comment]
> Thanks for reporting, it appears that Firefox attempts to load and execute the <script> tag before loading the and it causes all the interactions with the said html elements (getlEmentById, etc) to return null (uncaught exception). Although when I tested EXACT on Firefox before it worked fine.
> 
> Simply putting the script tag at the bottom of the html file (So that the is created before being accessed) solves this issue.
> 
> [Should work properly now, let me know if it's still not working](https://thraetaona.github.io/EXACT/)
> 
> [Relevant release](https://github.com/Thraetaona/EXACT/releases/tag/1.0.1)
