### ISSUE TITLE
Add AAM opcode undocumented usage?

### ISSUE THREAD

**Issue by eboregelna** [VioletVillain/ZedAssembly#2]
https://github.com/Thraetaona/EXACT/blob/20513bb0477d46d573fb92f039be50beb5a0c5ce/src/8086.wat#L3846C2-L3862C4

Per https://www.righto.com/2023/07/undocumented-8086-instructions.html the actual 8086 hardware allows divisors other than 10.

**Comment by Thraetaona** [comment]
Thank you for bringing this up; there was actually a bug within AAM (and AAD), too.

Because they are both two-byte instructions, hardcoding the second "operand" as `10` meant that the second byte was never accounted for.  By reading the next code byte and stepping through the instruction pointer once, we can replicate the undocumented behavior and also fix the emulator's own length mismatch bug.

I saw that this "reading over byte and stepping IP" code was repeated quite often in the code, so I placed it under `$fetch_byte` and `$fetch_word` boilerplate functions, reducing redundancy in lots of cases.

For future, it could be interesting to add both the `IND` and `OPR` *internal* registers, which could still get "accessed" and observed in a real 8086.

# I fixed this in commit 7f30fe9.
